// Demo data only — not used in client deployments.
import type { Archetype, ArchetypeKey, SiteConfig } from "@/config/design.config";

export const ARCHETYPES: Record<ArchetypeKey, Archetype> = {
	salon: {
		name: "Wren & Ivy",
		tagline: "Hair Studio · Established 2014",
		logoMark: "Scissors",
		hero: {
			eyebrow: "BY APPOINTMENT",
			headline: "A quiet salon for considered hair.",
			sub: "Color, cut, and care in a small studio on Mill Street. Two chairs, no rush, no upsell.",
			cta: "Book a chair",
			ctaIcon: "Calendar",
		},
		about: {
			title: "Twelve years on Mill Street.",
			body: "Wren & Ivy opened in 2014 as a two-chair studio with a simple idea: give people the time their hair deserves. We work by appointment only, take one guest at a time per stylist, and source low-tox color from independent suppliers.",
			badges: [
				{ icon: "Award", text: "12 years in business" },
				{ icon: "Shield", text: "Licensed & insured" },
				{ icon: "Heart", text: "Locally owned" },
			],
		},
		sectionHeadings: {
			services: "What we offer.",
			servicesSub: "Prices are starting points — we quote anything bigger before we begin.",
			gallery: "Recent work.",
			testimonials: "From guests who keep coming back.",
			hours: "This week.",
			contact: "Stop in or get in touch.",
		},
		services: [
			{
				icon: "Scissors",
				title: "Cut & style",
				desc: "Consultation, wash, precision cut, blow-dry finish.",
				price: "$95+",
			},
			{
				icon: "Sparkles",
				title: "Color",
				desc: "Single-process, gloss, or full balayage with a partner colorist.",
				price: "$160+",
			},
			{
				icon: "Brush",
				title: "Highlights",
				desc: "Full or partial foil work. Includes toner and treatment.",
				price: "$210+",
			},
			{
				icon: "Droplet",
				title: "Treatment",
				desc: "Bond repair or scalp therapy. Add to any service.",
				price: "$45",
			},
			{ icon: "Heart", title: "Bridal", desc: "On-site or studio styling for the wedding party.", price: "Quote" },
			{
				icon: "User",
				title: "First visit",
				desc: "New-guest consultation, includes a complimentary trim.",
				price: "$60",
			},
		],
		galleryCaptions: [
			"Before · soft cut",
			"Lived-in highlights",
			"The studio",
			"Tools",
			"Bridal styling",
			"Color station",
		],
		testimonials: [
			{
				quote: "I have been going here for six years. They actually listen, and my hair has never been healthier.",
				name: "Margaret L.",
				meta: "Guest since 2019",
				rating: 5,
			},
			{
				quote: "Found them after moving across the country. The first cut felt like coming home.",
				name: "Devon P.",
				meta: "Guest since 2023",
				rating: 5,
			},
			{
				quote: "Booked a balayage for my wedding. They were calm, kind, and the photos are still in my phone.",
				name: "Sara K.",
				meta: "Guest since 2022",
				rating: 5,
			},
		],
		hours: [
			["Monday", "Closed"],
			["Tuesday", "10:00 — 6:00"],
			["Wednesday", "10:00 — 6:00"],
			["Thursday", "10:00 — 8:00"],
			["Friday", "9:00 — 6:00"],
			["Saturday", "9:00 — 4:00"],
			["Sunday", "Closed"],
		],
		contact: {
			phone: "(503) 555-0142",
			email: "hello@wrenandivy.studio",
			address: "218 Mill Street, Suite B · Hood River, OR",
		},
		menu: null,
		images: {
			hero: "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=1600&q=80",
			about: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=900&q=80",
			gallery: [
				"https://images.unsplash.com/photo-1605497788044-5a32c7078486?w=600&q=75",
				"https://images.unsplash.com/photo-1562322140-8baeececf3df?w=600&q=75",
				"https://images.unsplash.com/photo-1560066984-138dadb4c035?w=600&q=75",
				"https://images.unsplash.com/photo-1633681926022-84c23e8cb2d6?w=600&q=75",
				"https://images.unsplash.com/photo-1521590832167-7bcbfaa6381f?w=600&q=75",
				"https://images.unsplash.com/photo-1580618672591-eb180b1a973f?w=600&q=75",
			],
			testimonialAvatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&q=75",
		},
	},
	plumber: {
		name: "Holloway & Sons",
		tagline: "Plumbing & Drain · Since 1978",
		logoMark: "Wrench",
		hero: {
			eyebrow: "24/7 EMERGENCY SERVICE",
			headline: "Honest plumbing, three generations in.",
			sub: "Family-owned since 1978. We work on residential and light commercial across the Willamette Valley. No trip charges in city limits.",
			cta: "Call (503) 555-0118",
			ctaIcon: "Phone",
		},
		about: {
			title: "A trade, not a sales pitch.",
			body: "My grandfather started Holloway in 1978 with one truck and a yellow-pages ad. Three generations later we still run six trucks, answer our own phone, and write fixed quotes before we touch a wrench.",
			badges: [
				{ icon: "Award", text: "47 years in business" },
				{ icon: "Shield", text: "Licensed · CCB #82014" },
				{ icon: "CheckCircle", text: "Bonded & insured" },
			],
		},
		sectionHeadings: {
			services: "What we do, and what we charge.",
			servicesSub: "Prices are starting points — we write a fixed quote before we touch anything.",
			gallery: "Recent work.",
			testimonials: "From people who keep calling us back.",
			hours: "This week.",
			contact: "Stop in or call us.",
		},
		services: [
			{
				icon: "Droplet",
				title: "Leak repair",
				desc: "Pipe, fixture, slab, and supply-line leaks. Same-day in most cases.",
				price: "From $145",
			},
			{
				icon: "Wrench",
				title: "Drain cleaning",
				desc: "Sink, tub, and main-line clearing with a camera follow-up.",
				price: "From $189",
			},
			{
				icon: "Flame",
				title: "Water heater",
				desc: "Tank, tankless, and hybrid replacement and service.",
				price: "Quote",
			},
			{
				icon: "Shield",
				title: "Re-pipe",
				desc: "Whole-home PEX or copper re-piping with a 25-year warranty.",
				price: "Quote",
			},
			{
				icon: "Sparkles",
				title: "Fixture install",
				desc: "Faucets, toilets, disposals — bring it home, we will set it.",
				price: "From $225",
			},
			{
				icon: "Phone",
				title: "Emergency",
				desc: "24-hour response for burst pipes and overflowing drains.",
				price: "$220 + work",
			},
		],
		galleryCaptions: [
			"New install · kitchen",
			"Tankless retrofit",
			"Drain camera",
			"The shop",
			"Crew",
			"Before · after",
		],
		testimonials: [
			{
				quote: "Called at 6am with a burst supply line. Truck was here by 7:15. They quoted before they cut and the bill matched.",
				name: "Trevor B.",
				meta: "Salem, residential",
				rating: 5,
			},
			{
				quote: "Re-piped our 1962 ranch. Crew was tidy, on time, and the price did not move from the quote.",
				name: "The Aldis",
				meta: "Albany, residential",
				rating: 5,
			},
			{
				quote: "Three generations of Hollowayes have worked on this restaurant. That should tell you everything.",
				name: "Mira at Olive & Oak",
				meta: "Commercial, since 2003",
				rating: 5,
			},
		],
		hours: [
			["Monday", "7:00 — 5:00"],
			["Tuesday", "7:00 — 5:00"],
			["Wednesday", "7:00 — 5:00"],
			["Thursday", "7:00 — 5:00"],
			["Friday", "7:00 — 5:00"],
			["Saturday", "8:00 — 2:00"],
			["Sunday", "Emergency only"],
		],
		contact: {
			phone: "(503) 555-0118",
			email: "dispatch@hollowayplumbing.com",
			address: "1402 SE Industrial Way · Salem, OR",
		},
		menu: null,
		images: {
			hero: "https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=1600&q=80",
			about: "https://images.unsplash.com/photo-1581094288338-2314dddb7ece?w=900&q=80",
			gallery: [
				"https://images.unsplash.com/photo-1607400201515-c2c41c07d307?w=600&q=75",
				"https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=600&q=75",
				"https://images.unsplash.com/photo-1581094288338-2314dddb7ece?w=600&q=75",
				"https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=600&q=75",
				"https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=600&q=75",
				"https://images.unsplash.com/photo-1620626011761-996317b8d101?w=600&q=75",
			],
			testimonialAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&q=75",
		},
	},
	taco: {
		name: "El Pastor Truck",
		tagline: "Tacos al Pastor · Since 2018",
		logoMark: "Truck",
		hero: {
			eyebrow: "WED — SUN · 11AM TILL WE RUN OUT",
			headline: "Tacos al pastor, on a corner, in a truck.",
			sub: "Trompo every morning. Tortillas pressed to order. Park behind the brewery on Williams Ave — the line moves quick.",
			cta: "See the menu",
			ctaIcon: "ChevronDown",
		},
		about: {
			title: "One truck, one trompo, one recipe.",
			body: "We started El Pastor in 2018 with a borrowed trompo and a recipe my mom wrote on the back of an envelope. We have not changed it since. Marinate overnight, spin the trompo from 9am, call it a day when the meat runs out.",
			badges: [
				{ icon: "Flame", text: "Trompo-spit cooked" },
				{ icon: "Heart", text: "Family recipe" },
				{ icon: "CheckCircle", text: "Health-graded A" },
			],
		},
		sectionHeadings: {
			services: "Where to find us.",
			servicesSub: "On a corner, at a brewery, or at your event — we keep it simple.",
			gallery: "From the truck.",
			testimonials: "What regulars say.",
			hours: "This week.",
			contact: "Find us or reach out.",
		},
		services: [
			{
				icon: "Truck",
				title: "On the corner",
				desc: "Wed–Sun · Williams Ave & N Mason · 11am til sold out.",
				price: "",
			},
			{
				icon: "Calendar",
				title: "Catering",
				desc: "Weddings, office lunches, backyard parties. 25-guest min.",
				price: "From $14/guest",
			},
			{
				icon: "Coffee",
				title: "Pop-ups",
				desc: "We park at breweries on rotation — check the calendar.",
				price: "",
			},
			{
				icon: "Flame",
				title: "Trompo to-go",
				desc: "Whole-trompo orders for events. 48-hour notice.",
				price: "Quote",
			},
		],
		galleryCaptions: [
			"The trompo",
			"Tortillas, fresh",
			"Williams Ave queue",
			"Salsa lineup",
			"Catering · 60 guests",
			"Behind the line",
		],
		testimonials: [
			{
				quote: "Best pastor in the city, and that is the whole review. Park your car, get six.",
				name: "Andrés R.",
				meta: "Regular since 2019",
				rating: 5,
			},
			{
				quote: "Catered our wedding. Sixty people. Not a single taco hit the floor.",
				name: "Hannah & Jules",
				meta: "Wedding, 2024",
				rating: 5,
			},
			{
				quote: "I have driven across town in the rain for these. Worth it every time.",
				name: "Mike D.",
				meta: "Lives in Lake O",
				rating: 5,
			},
		],
		hours: [
			["Monday", "Closed"],
			["Tuesday", "Closed"],
			["Wednesday", "11:00 — sold out"],
			["Thursday", "11:00 — sold out"],
			["Friday", "11:00 — sold out"],
			["Saturday", "11:00 — sold out"],
			["Sunday", "11:00 — sold out"],
		],
		contact: {
			phone: "(971) 555-0162",
			email: "orders@elpastortruck.com",
			address: "Williams Ave & N Mason · Portland, OR",
		},
		menu: {
			sectionTitle: "What's on the trompo today.",
			categories: [
				{
					name: "Tacos",
					items: [
						{
							name: "Al Pastor",
							desc: "Marinated pork shoulder, pineapple, white onion, cilantro.",
							price: "$4.50",
							image: "https://images.unsplash.com/photo-1683062332605-4e1209d75346?q=80&w=2736&auto=format&fit=crop",
						},
						{
							name: "Carnitas",
							desc: "Slow-braised pork, salsa verde, white onion, cilantro.",
							price: "$4.50",
							image: "https://images.unsplash.com/photo-1683062332605-4e1209d75346",
						},
						{
							name: "Pollo Asado",
							desc: "Grilled chicken thigh, salsa roja, lime crema.",
							price: "$4.25,",
							image: "https://images.unsplash.com/photo-1683062332605-4e1209d75346",
						},
						{
							name: "Hongos",
							desc: "Marinated mushrooms, charred poblano, queso fresco. (v)",
							price: "$4.25",
							image: "https://images.unsplash.com/photo-1683062332605-4e1209d75346",
						},
					],
				},
				{
					name: "Plates",
					items: [
						{
							name: "Trompo Plate",
							desc: "Three pastor tacos, rice, frijoles charros, two salsas.",
							price: "$15",
							image: "https://images.unsplash.com/photo-1539136788836-5699e78bfc75",
						},
						{
							name: "Mixed Plate",
							desc: "Pick three tacos, rice, beans, chips, salsa lineup.",
							price: "$15",
							image: "https://images.unsplash.com/photo-1539136788836-5699e78bfc75",
						},
						{
							name: "Taco Salad",
							desc: "Bowl of greens, rice, beans, choice of meat, all the salsas.",
							price: "$13",
							image: "https://images.unsplash.com/photo-1539136788836-5699e78bfc75",
						},
					],
				},
				{
					name: "Sides & Drinks",
					items: [
						{
							name: "Frijoles charros",
							desc: "Stewed pinto beans with bacon and chiles.",
							price: "$5",
							image: "https://images.unsplash.com/photo-1669867405064-f31e8707216e",
						},
						{
							name: "Elote",
							desc: "Grilled corn, mayo, cotija, tajín, lime.",
							price: "$5",
							image: "https://images.unsplash.com/photo-1669867405064-f31e8707216e",
						},
						{
							name: "Horchata",
							desc: "House-made daily. Cinnamon, rice, milk.",
							price: "$4",
							image: "https://images.unsplash.com/photo-1669867405064-f31e8707216e",
						},
						{
							name: "Jarritos",
							desc: "Tamarindo, mandarina, or fresa.",
							price: "$3",
							image: "https://images.unsplash.com/photo-1669867405064-f31e8707216e",
						},
					],
				},
			],
		},
		images: {
			hero: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=1600&q=80",
			about: "https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=900&q=80",
			gallery: [
				"https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=600&q=75",
				"https://images.unsplash.com/photo-1599974579688-8dbdd335c77f?w=600&q=75",
				"https://images.unsplash.com/photo-1611250188496-e966043a0629?w=600&q=75",
				"https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=600&q=75",
				"https://images.unsplash.com/photo-1542444256-714f0b4a7d2d?w=600&q=75",
				"https://images.unsplash.com/photo-1607349913338-fca6f7fc42d0?w=600&q=75",
			],
			testimonialAvatar: "https://images.unsplash.com/photo-1607746882042-944635dfe10e?w=200&q=75",
		},
	},
};

export const DEFAULT_CONFIG: SiteConfig = {
	archetype: "salon",
	palette: "stone",
	fontPair: "fraunces",
	radius: 1,
	logoKind: "icon",
	filledImagery: true,
	menuVariant: "tabs",
	menuItemsPictures: false,
};
